### ISSUE TITLE
[2pt] New Reservation Form

### ISSUE THREAD

**Issue by badger-99** [Zilola-Nazarova/workspace-reservation-front-end#7]
- Create a reservation form for workspaces with the following fields:
  - Username
  - Workspace
  - City (drop-down menu)
  - Start Date
  - End Date (Same as start date if reserving only one day)
- If the user is not logged in, show them links to either log-in or sign-up
- Only the Username should be auto-filled when navigating to this form from the Nav panel.
- Only the Username and the Workspace should be auto-filled when navigating to this page from the Workspace details page
- (Optional) On submission compile all the form data into a JSON file and write it to a file. This is to test that the data is being correctly formatted, later the JSON data will be sent through an API endpoint in a POST request
- (Optional) Consider giving feedback to the user on either success or failure

**Comment by wickathou** [comment]
[Backend](https://github.com/badger-99/workspace-reservation-back-end/pull/26)

[Frontend](https://github.com/Zilola-Nazarova/workspace-reservation-front-end/pull/23)
